query ComponentsInConferences($date: String) {
  conferences(filter: {publishedSince: $date}) {
    ... on Conference {
      id
      __typename
      groupChatId
      startDate
      endDate
      title {
        translation(locale: "pt-BR")
      }
      slug
      components {
        id
        __typename
        name {
          translation(locale: "pt-BR")
        }
      }
    }
  }
}
