FROM python:3.10-slim

WORKDIR /py-env

COPY ./requirements* /py-env

RUN pip3 install -r requirements.testing.txt && pip3 install -r requirements.txt

WORKDIR /py-app
COPY setup* .
COPY pyproject.toml .

COPY tests tests
COPY dags dags
COPY plugins plugins
