FROM python:3.9-slim

WORKDIR /py-env

COPY ./requirements* /py-env

RUN pip3 install -r requirements.testing.txt && pip3 install -r requirements.txt

WORKDIR /py-app
COPY setup* .
COPY pyproject.toml .
