query teste ($start_date: String!, $end_date: String!) {
  participatoryProcesses  {
    title{
      translations{
        text
      }
    }
    slug
    components{
      id
      ... on Proposals   {
        __typename
        name {
          translations {
            text
          }
        }
        proposals (filter:  {publishedSince: $start_date, publishedBefore: $end_date}  ) {
          nodes {
            id
            createdAt
            publishedAt
            updatedAt
            attachments{
              thumbnail
              type
              url
            }
            author{
              id
              name
              nickname
              organizationName
            }
            body{
              translations{
                text
              }
            }
            category{
              id
              name{
                translations{
                  text
                }
              }
            }

            authorsCount
            userAllowedToComment
            endorsementsCount
            totalCommentsCount
            versionsCount
            voteCount
            commentsHaveAlignment
            commentsHaveVotes
            createdInMeeting
            hasComments
            official
            fingerprint{
              source
              value
            }
            position
            reference
            scope{
              id
              name{
                translations{
                  text
                }
              }
            }
            state
            title{
              translations{
                text
              }
            }
          }
        }
      }
    }
  }
}
