query get_proposal_by_id($component_id: ID!, $id: ID!) {
  component(id: $component_id) {
    id
    name{
      translations{
        text
      }
    }
    participatorySpace {
      id
      title {
        translations {
          text
        }
      }
    }
    ... on Proposals {
      proposal(id: $id) {
          id
          createdAt
          publishedAt
          updatedAt
          attachments {
            thumbnail
            type
            url
          }
          author {
            id
            name
            nickname
            organizationName
          }
          body {
            translations {
              text
            }
          }
          category {
            id
            name {
              translations {
                text
              }
            }
          }
          authorsCount
          userAllowedToComment
          endorsementsCount
          totalCommentsCount
          versionsCount
          voteCount
          commentsHaveAlignment
          commentsHaveVotes
          createdInMeeting
          hasComments
          official
          fingerprint {
            source
            value
          }
          position
          reference
          scope {
            id
            name {
              translations {
                text
              }
            }
          }
          state
          title {
            translations {
              text
            }
          }
      }
    }
  }
}
