query meetingQuery {
  participatoryProcesses {
    title {
      translations {
        text
      }
    }
    components(filter: {type: "Meetings"}){
      id
      ... on Meetings {
        id
        meetings {
          nodes {
            id
            comments{
              body
            }
            	comments{
                body
              }
          }
        }
      }
    }
  }
}
