query Survey {
  participatoryProcesses {
    title {
      translation(locale: "pt-BR")
    }
    components(filter: {type: "Surveys"}) {
      id
      __typename
      ... on Surveys {
        name {
          translation(locale: "pt-BR")
        }
        surveys(first: 1) {
          nodes {
            createdAt
            questionnaire {
              title {
                translations {
                  text
                }
              }
              questions {
                answerOptions {
                  body {
                    translations {
                      text
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
