query get_updat_at_proposals($id: ID!, $page: String!) {
  component(id: $id) {
    id
    ... on Proposals {
      proposals(
          order: { publishedAt: "asc" }
          after: $page
        ) {
          pageInfo {
            hasNextPage
            startCursor
            endCursor
          }
          nodes {
            id
            updatedAt
          }
        }
    }
  }
}
