query get_updat_at_proposals {
  participatoryProcesses  {
    components{
      ... on Proposals   {
        proposals {
       nodes{
        id
        updatedAt
      		}
        }
      }
    }
  }
}