CREATE TABLE IF NOT EXISTS {schema}.{table_name} (
	main_title text NULL,
	component_id int8 NULL,
	component_name text NULL,
	proposal_id int8 NOT NULL,
	proposal_created_at timestamp NULL,
	proposal_published_at timestamp NULL,
	proposal_updated_at timestamp NULL,
	author_name text NULL,
	author_nickname text NULL,
	author_organization text NULL,
	proposal_body text NULL,
	category_name text NULL,
	proposal_title text NULL,
	authors_count int8 NULL,
	user_allowed_to_comment bool NULL,
	endorsements_count int8 NULL,
	total_comments_count int8 NULL,
	versions_count int8 NULL,
	vote_count int8 NULL,
	comments_have_alignment bool NULL,
	comments_have_votes bool NULL,
	created_in_meeting bool NULL,
	has_comments bool NULL,
	official bool NULL,
	fingerprint text NULL,
	"position" int8 NULL,
	reference text NULL,
	"scope" text NULL,
	state text NULL,
	event_day_id int8 NULL,
	available_day_id int8 NULL,
	available_month_id int8 NULL,
	available_year_id int8 NULL,
	writing_day_id int8 NULL
);
