query PropostasPaginadas($id: ID!, $start_date: String, $end_date: String, $page: String) {
  component(id: $id) {
    id
    participatorySpace {
      id
      type
      __typename
    }
    name {
      translation(locale: "pt-BR")
    }
    ... on Proposals {
      id
      name {
        translation(locale: "pt-BR")
      }
      proposals(
        filter: { publishedSince: $start_date, publishedBefore: $end_date }
        order: { publishedAt: "asc" }
        after: $page
      ) {
        pageInfo {
          hasNextPage
          startCursor
          endCursor
        }
        nodes {
          id
          title {
            translation(locale: "pt-BR")
          }
          publishedAt
          updatedAt
          state
          totalCommentsCount
          voteCount
          category {
            id
            name {
              translation(locale: "pt-BR")
            }
          }
        }
      }
    }
  }
}
