query comments_in_proposals($id: ID!, $page: String) {
  component(id: $id) {
    name {
      translation(locale: "pt-BR")
    }
    ... on Proposals {
      proposals(after: $page) {
        pageInfo {
          hasNextPage
          startCursor
          endCursor
        }
        nodes {
          id
          comments {
            id
            author {
              id
              name
            }
            createdAt
            updatedAt
            body
            upVotes
            downVotes
          }
        }
      }
    }
  }
}
