query Comments($id: ID!) {
  commentable(
    id: $id
    type: "Decidim::Comments::Comment"
    locale: "pt-BR"
    toggleTranslations: true
  ) {
    id
    comments {
      id
      body
      createdAt
      author {
        id
        name
      }
    }
  }
}
