query ComponentsInParticipatoryProcess($date: String) {
  participatoryProcesses(filter: {publishedSince: $date}) {
    ... on ParticipatoryProcess {
      slug
      __typename
      components {
        id
        __typename
      }
    }
  }
}
