query meetingQuery (id: ID!) {
  component(id: $id) {
    participatorySpace {
      id
      title {
         translation(locale: "pt-BR")
      }
    }
    name {
      translation(locale: "pt-BR")
    }
    ... on Meetings {
      meetings {
        nodes {
          id
          category {
            id
            name {
              translation(locale: "pt-BR")
            }
          }
          contributionCount
          totalCommentsCount
          startTime
          endTime
          attendeeCount
          locationHints {
            translation(locale: "pt-BR")
          }
          coordinates{
            latitude
            longitude
          }
        }
      }
    }
  }
}