dbt_pg_project:
  outputs:
    dev:
      dbname: dex_lake_staging
      host: 35.231.218.194
      pass: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: 5432
      schema: lappis
      threads: 4
      type: postgres
      user: dex_lake_staging
  target: dev