dbt_pg_project:
  outputs:
    dev:
      dbname: data_warehouse
      schema: raw
      host: localhost
      user: postgres_dw
      pass: postgres_dw
      port: 25570
      threads: 4
      type: postgres
  target: dev